include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    always_specify_types: true
    avoid_positional_boolean_parameters: false
    avoid_types_on_closure_parameters: false
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
